name: Sample Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
  - cron: "0 7 * * 0,6"
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: /
  
  second-job:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
